-- Add columns for tags and error messages to the automations table.
ALTER TABLE public.automations
  ADD COLUMN tags TEXT[],
  ADD COLUMN error_message TEXT;

-- Update the status CHECK constraint to include 'pending' and set it as the default.
-- To modify a check constraint, you must drop the old one and add a new one.
ALTER TABLE public.automations
  DROP CONSTRAINT automations_status_check;

ALTER TABLE public.automations
  ADD CONSTRAINT automations_status_check
  CHECK (status IN ('pending', 'generating', 'completed', 'failed'));

ALTER TABLE public.automations
    ALTER COLUMN status SET DEFAULT 'pending';

-- Add comments for the new columns.
COMMENT ON COLUMN public.automations.tags IS 'Searchable tags generated by AI for filtering and SEO.';
COMMENT ON COLUMN public.automations.error_message IS 'Stores any error messages from the generation process.';


-- Create the junction table to link automations and tools.
CREATE TABLE public.automation_tools (
  automation_id UUID NOT NULL,
  tool_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT automation_tools_pkey PRIMARY KEY (automation_id, tool_id),
  CONSTRAINT automation_tools_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES public.automations(id) ON DELETE CASCADE,
  CONSTRAINT automation_tools_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tools(id) ON DELETE CASCADE
);

-- Add indexes for performance.
CREATE INDEX idx_automation_tools_automation_id ON public.automation_tools(automation_id);
CREATE INDEX idx_automation_tools_tool_id ON public.automation_tools(tool_id);

-- Enable RLS for the new table.
ALTER TABLE public.automation_tools ENABLE ROW LEVEL SECURITY;

-- RLS Policies for automation_tools.
-- Allow read access for automations that the user can already see.
CREATE POLICY "Users can view tools for their visible automations"
  ON public.automation_tools
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM automations
      WHERE automations.id = automation_tools.automation_id
    )
  );

-- Server-side insertions will bypass RLS, but this policy allows users to insert if needed.
CREATE POLICY "Users can insert tool links for their own automations"
  ON public.automation_tools
  FOR INSERT
  WITH CHECK (
    (
      SELECT user_id
      FROM automations
      WHERE id = automation_id
    ) = auth.uid()
  );

COMMENT ON TABLE public.automation_tools IS 'Links automations to the tools they use.'; 